# Generated by Django 2.1.7 on 2019-03-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190320_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='resmanage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='resmanage',
            name='dp',
            field=models.ManyToManyField(to='login.Department'),
        ),
    ]
