# Generated by Django 2.1.7 on 2019-03-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190321_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resmanage',
            name='resip',
            field=models.GenericIPAddressField(protocol='ipv4'),
        ),
    ]
