# Generated by Django 2.1.7 on 2019-04-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_testredis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testredis',
            old_name='vlaue',
            new_name='value',
        ),
    ]
