# Generated by Django 2.1.7 on 2019-03-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190322_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='group_menu',
            new_name='pid',
        ),
    ]
